// vue-ui/src/views/ProjectEdit.vue
<template>
  <div class="min-h-screen bg-gray-100 py-8">
    <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header -->
      <div class="mb-8">
        <button
          @click="goBack"
          class="inline-flex items-center text-blue-600 hover:text-blue-700 mb-4"
        >
          <svg class="w-5 h-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
          </svg>
          Back to Dashboard
        </button>
        <h1 class="text-3xl font-bold text-gray-900">Edit Project</h1>
      </div>

      <!-- Form -->
      <div v-if="project" class="bg-white rounded-lg shadow-md p-6">
        <form @submit.prevent="handleSubmit">
          <!-- Project Name -->
          <div class="mb-6">
            <label for="name" class="block text-sm font-medium text-gray-700 mb-2">
              Project Name <span class="text-red-500">*</span>
            </label>
            <input
              id="name"
              v-model="formData.name"
              type="text"
              required
              class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
              placeholder="Enter project name"
            />
          </div>

          <!-- Description -->
          <div class="mb-6">
            <label for="description" class="block text-sm font-medium text-gray-700 mb-2">
              Description
            </label>
            <textarea
              id="description"
              v-model="formData.description"
              rows="3"
              class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
              placeholder="Enter project description (optional)"
            ></textarea>
          </div>

          <!-- Source Type -->
          <div class="mb-6">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Source Type <span class="text-red-500">*</span>
            </label>
            <div class="space-y-2">
              <label class="flex items-center">
                <input
                  v-model="formData.sourceType"
                  type="radio"
                  value="local"
                  class="mr-2"
                />
                <span>Local Folder</span>
              </label>
              <label class="flex items-center">
                <input
                  v-model="formData.sourceType"
                  type="radio"
                  value="google-drive"
                  class="mr-2"
                />
                <span>Google Drive</span>
              </label>
            </div>
          </div>

          <!-- Folder Path -->
          <div class="mb-6">
            <label for="folderPath" class="block text-sm font-medium text-gray-700 mb-2">
              Folder Path <span class="text-red-500">*</span>
            </label>
            <div class="flex gap-2">
              <input
                id="folderPath"
                v-model="formData.folderPath"
                type="text"
                required
                class="flex-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                :placeholder="formData.sourceType === 'local' ? '/path/to/dhf/folder' : 'Google Drive folder ID'"
              />
              <button
                v-if="formData.sourceType === 'google-drive'"
                type="button"
                @click="showFolderPicker = true"
                class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors whitespace-nowrap"
              >
                Browse
              </button>
            </div>
            <p class="mt-1 text-sm text-gray-500">
              {{ formData.sourceType === 'local' ? 'Enter the absolute path to your DHF folder' : 'Click Browse to select your Google Drive folder' }}
            </p>
            <p v-if="selectedFolderName" class="mt-1 text-sm text-blue-600">
              Selected: {{ selectedFolderName }}
            </p>
          </div>

          <!-- Target Dates -->
          <div class="mb-6">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Target Dates (Optional)
            </label>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label for="phase1" class="block text-xs text-gray-600 mb-1">Phase 1</label>
                <input
                  id="phase1"
                  v-model="formData.targetDates.phase1"
                  type="date"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label for="phase2" class="block text-xs text-gray-600 mb-1">Phase 2</label>
                <input
                  id="phase2"
                  v-model="formData.targetDates.phase2"
                  type="date"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label for="phase3" class="block text-xs text-gray-600 mb-1">Phase 3</label>
                <input
                  id="phase3"
                  v-model="formData.targetDates.phase3"
                  type="date"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label for="phase4" class="block text-xs text-gray-600 mb-1">Phase 4</label>
                <input
                  id="phase4"
                  v-model="formData.targetDates.phase4"
                  type="date"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>
          </div>

          <!-- Action Buttons -->
          <div class="flex justify-end space-x-4">
            <button
              type="button"
              @click="goBack"
              class="px-6 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
            >
              Save Changes
            </button>
          </div>
        </form>
      </div>

      <!-- Loading State -->
      <div v-else class="bg-white rounded-lg shadow-md p-12 text-center">
        <p class="text-gray-500">Loading project...</p>
      </div>
    </div>

    <!-- Google Drive Folder Picker Modal -->
    <GoogleDriveFolderPicker
      :is-open="showFolderPicker"
      @close="showFolderPicker = false"
      @select="handleFolderSelect"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useProjectService } from '../composables/useProjectService';
import { Project } from '../models/project.model';
import GoogleDriveFolderPicker from '../components/GoogleDriveFolderPicker.vue';

const router = useRouter();
const route = useRoute();
const projectService = useProjectService();

const project = ref<Project | null>(null);
const showFolderPicker = ref(false);
const selectedFolderName = ref<string>('');

const formData = ref({
  name: '',
  description: '',
  sourceType: 'local' as 'local' | 'google-drive',
  folderPath: '',
  targetDates: {
    phase1: '',
    phase2: '',
    phase3: '',
    phase4: ''
  }
});

onMounted(() => {
  const projectId = route.params.id as string;
  project.value = projectService.getProject(projectId);
  
  if (project.value) {
    formData.value = {
      name: project.value.name,
      description: project.value.description || '',
      sourceType: project.value.sourceType,
      folderPath: project.value.folderPath,
      targetDates: {
        phase1: project.value.targetDates?.phase1 || '',
        phase2: project.value.targetDates?.phase2 || '',
        phase3: project.value.targetDates?.phase3 || '',
        phase4: project.value.targetDates?.phase4 || ''
      }
    };
  }
});

const handleFolderSelect = (folderId: string, folderName: string) => {
  formData.value.folderPath = folderId;
  selectedFolderName.value = folderName;
  showFolderPicker.value = false;
};

const handleSubmit = () => {
  if (!project.value) return;

  projectService.updateProject(project.value.id, {
    name: formData.value.name,
    description: formData.value.description,
    sourceType: formData.value.sourceType,
    folderPath: formData.value.folderPath,
    targetDates: {
      phase1: formData.value.targetDates.phase1 || undefined,
      phase2: formData.value.targetDates.phase2 || undefined,
      phase3: formData.value.targetDates.phase3 || undefined,
      phase4: formData.value.targetDates.phase4 || undefined
    }
  });

  router.push(`/projects/${project.value.id}`);
};

const goBack = () => {
  if (project.value) {
    router.push(`/projects/${project.value.id}`);
  } else {
    router.push('/');
  }
};
</script>

// angular-ui/src/app/components/project-edit/project-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ProjectService } from '../../services/project.service';
import { Project } from '../../models/project.model';
import { GoogleDrivePickerComponent } from '../google-drive-picker/google-drive-picker.component';

@Component({
  selector: 'app-project-edit',
  templateUrl: './project-edit.component.html',
  styleUrls: ['./project-edit.component.css'],
  imports: [CommonModule, FormsModule, GoogleDrivePickerComponent],
  standalone: true
})
export class ProjectEditComponent implements OnInit {
  project: Project | null = null;
  projectName: string = '';
  projectDescription: string = '';
  folderPath: string = '';
  selectedSource: 'local' | 'google-drive' = 'local';
  showGoogleDrivePicker = false;
  googleDriveAccessToken: string = '';
  notFound = false;
  phase1Date: string = '';
  phase2Date: string = '';
  phase3Date: string = '';
  phase4Date: string = '';
  
  fileSources = [
    { value: 'local', label: 'Local Filesystem', icon: '💻' },
    { value: 'google-drive', label: 'Google Drive', icon: '📁' }
  ];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private projectService: ProjectService
  ) {}

  ngOnInit(): void {
    const projectId = this.route.snapshot.paramMap.get('id');
    if (projectId) {
      this.project = this.projectService.getProject(projectId);
      if (this.project) {
        this.projectName = this.project.name;
        this.projectDescription = this.project.description || '';
        this.folderPath = this.project.folderPath;
        this.selectedSource = this.project.sourceType;
        this.googleDriveAccessToken = this.project.credentials?.accessToken || '';
        this.phase1Date = this.project.targetDates?.phase1 || '';
        this.phase2Date = this.project.targetDates?.phase2 || '';
        this.phase3Date = this.project.targetDates?.phase3 || '';
        this.phase4Date = this.project.targetDates?.phase4 || '';
      } else {
        this.notFound = true;
      }
    } else {
      this.notFound = true;
    }
  }

  onSourceChange(): void {
    this.folderPath = '';
  }

  openGoogleDrivePicker(): void {
    this.showGoogleDrivePicker = true;
  }

  onGoogleDriveFolderSelected(data: { folderId: string; folderName: string; accessToken: string }): void {
    this.folderPath = data.folderId;
    this.googleDriveAccessToken = data.accessToken;
    this.showGoogleDrivePicker = false;
  }

  onGoogleDrivePickerCancelled(): void {
    this.showGoogleDrivePicker = false;
  }

  saveProject(): void {
    if (!this.project || !this.projectName.trim() || !this.folderPath.trim()) {
      return;
    }

    this.projectService.updateProject(this.project.id, {
      name: this.projectName.trim(),
      description: this.projectDescription.trim() || undefined,
      folderPath: this.folderPath.trim(),
      sourceType: this.selectedSource,
      credentials: this.selectedSource === 'google-drive' && this.googleDriveAccessToken
        ? { accessToken: this.googleDriveAccessToken }
        : undefined,
      targetDates: {
        phase1: this.phase1Date || undefined,
        phase2: this.phase2Date || undefined,
        phase3: this.phase3Date || undefined,
        phase4: this.phase4Date || undefined
      }
    });

    this.router.navigate(['/projects', this.project.id]);
  }

  cancel(): void {
    if (this.project) {
      this.router.navigate(['/projects', this.project.id]);
    } else {
      this.router.navigate(['/']);
    }
  }
}

<div class="min-h-screen bg-gray-100 py-8">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
    <!-- Header -->
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-900 mb-2">Edit Project</h1>
      <p class="text-gray-600">Update your project settings</p>
    </div>

    <!-- Not Found -->
    <div *ngIf="notFound" class="bg-white rounded-lg shadow-md p-12 text-center">
      <h3 class="text-xl font-semibold text-gray-900 mb-2">Project Not Found</h3>
      <p class="text-gray-600 mb-6">The project you're trying to edit doesn't exist</p>
      <button
        (click)="cancel()"
        class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
      >
        Go to Projects
      </button>
    </div>

    <!-- Form -->
    <div *ngIf="!notFound" class="bg-white rounded-lg shadow-md p-6">
      <form (ngSubmit)="saveProject()" class="space-y-6">
        <!-- Project Name -->
        <div>
          <label for="projectName" class="block text-sm font-medium text-gray-700 mb-2">
            Project Name <span class="text-red-500">*</span>
          </label>
          <input
            id="projectName"
            [(ngModel)]="projectName"
            name="projectName"
            type="text"
            placeholder="e.g., Cardiac Monitor Device - DHF Analysis"
            class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            required
          />
        </div>

        <!-- Project Description -->
        <div>
          <label for="projectDescription" class="block text-sm font-medium text-gray-700 mb-2">
            Description (optional)
          </label>
          <textarea
            id="projectDescription"
            [(ngModel)]="projectDescription"
            name="projectDescription"
            rows="3"
            placeholder="Brief description of the medical device or project"
            class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          ></textarea>
        </div>

        <!-- File Source -->
        <div>
          <label for="sourceType" class="block text-sm font-medium text-gray-700 mb-2">
            DHF Location <span class="text-red-500">*</span>
          </label>
          <select
            id="sourceType"
            [(ngModel)]="selectedSource"
            name="sourceType"
            (change)="onSourceChange()"
            class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white"
          >
            <option *ngFor="let source of fileSources" [value]="source.value">
              {{ source.icon }} {{ source.label }}
            </option>
          </select>
          <p class="mt-1 text-sm text-gray-500">
            Select where your Design History File documents are stored
          </p>
        </div>

        <!-- Google Drive Browse Button -->
        <div *ngIf="selectedSource === 'google-drive'">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            DHF Folder <span class="text-red-500">*</span>
          </label>
          <div class="flex space-x-2">
            <input
              type="text"
              [value]="folderPath ? 'Folder Selected: ' + folderPath : 'No folder selected'"
              class="flex-1 px-4 py-2 border border-gray-300 rounded-md bg-gray-50"
              readonly
            />
            <button
              type="button"
              (click)="openGoogleDrivePicker()"
              class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors font-medium whitespace-nowrap"
            >
              📁 Browse
            </button>
          </div>
          <p class="mt-1 text-sm text-gray-500">
            Click "Browse" to select a Google Drive folder
          </p>
        </div>

        <!-- Local Filesystem Path Input -->
        <div *ngIf="selectedSource === 'local'">
          <label for="folderPath" class="block text-sm font-medium text-gray-700 mb-2">
            DHF Folder Path <span class="text-red-500">*</span>
          </label>
          <input
            id="folderPath"
            [(ngModel)]="folderPath"
            name="folderPath"
            type="text"
            placeholder="/path/to/dhf/documents"
            class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            required
          />
          <p class="mt-1 text-sm text-gray-500">
            Enter the full path to your Design History File folder
          </p>
        </div>

        <!-- Target Dates -->
        <div class="border-t border-gray-200 pt-6">
          <h3 class="text-sm font-medium text-gray-700 mb-4">Target Dates (Optional)</h3>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label for="phase1Date" class="block text-sm text-gray-600 mb-1">
                Phase 1 Target
              </label>
              <input
                id="phase1Date"
                [(ngModel)]="phase1Date"
                name="phase1Date"
                type="date"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
              />
            </div>
            <div>
              <label for="phase2Date" class="block text-sm text-gray-600 mb-1">
                Phase 2 Target
              </label>
              <input
                id="phase2Date"
                [(ngModel)]="phase2Date"
                name="phase2Date"
                type="date"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
              />
            </div>
            <div>
              <label for="phase3Date" class="block text-sm text-gray-600 mb-1">
                Phase 3 Target
              </label>
              <input
                id="phase3Date"
                [(ngModel)]="phase3Date"
                name="phase3Date"
                type="date"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
              />
            </div>
            <div>
              <label for="phase4Date" class="block text-sm text-gray-600 mb-1">
                Phase 4 Target
              </label>
              <input
                id="phase4Date"
                [(ngModel)]="phase4Date"
                name="phase4Date"
                type="date"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
              />
            </div>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="flex justify-end space-x-3 pt-4 border-t border-gray-200">
          <button
            type="button"
            (click)="cancel()"
            class="px-6 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            [disabled]="!projectName.trim() || !folderPath.trim()"
            class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Save Changes
          </button>
        </div>
      </form>
    </div>

    <!-- Google Drive Picker Modal -->
    <app-google-drive-picker
      *ngIf="showGoogleDrivePicker"
      [isProcessing]="false"
      (folderSelected)="onGoogleDriveFolderSelected($event)"
      (cancelled)="onGoogleDrivePickerCancelled()"
    ></app-google-drive-picker>
  </div>
</div>
